VendorVillage/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('mall/', include('mall.urls', namespace='mall')),
    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls)

]
if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *
from .token_view import (
    CustomTokenRefreshView
)

app_name = 'accounts'

urlpatterns = [
    path('', views.account, name='account'),
    path('register/', views.register, name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_business/', views.my_business, name='my_business'),
]

# API
urlpatterns.extend([
    path('api/auth/register/', RegisterView.as_view(), name='register'),
    path('api/auth/login/', LoginView.as_view(), name='login'),
    path('api/auth/logout/', views.logout_api, name='logout'),
    path('api/account/', views.account_info, name='account-info'),
    path('api/auth/me/', views.me, name='check_auth'),
    path('api/token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('api/business/check-access/<str:business_slug>/', check_business_access, name='check_business_access'),
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
])

core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views
from . import business_API
from . import business_product_CRUD_API
from . import sale_product_API
from . import analytics_API
from . import settings_API
from . import receipt_API

app_name = "core"
urlpatterns = [
    path("", views.home, name="main"),
    path(
        "bussiness_categories",
        views.bussiness_categories_list,
        name="bussiness_categories_list",
    ),
    path("business/edit/<int:pk>/", views.edit_business, name="edit_business"),
    path("sites/", views.sites, name="sites"),
    path("site/<slug:slug>/", views.business_site, name="site"),
]
# API
urlpatterns.extend(
    [
        path(
            "api/business-categories/",
            views.business_categories_api,
            name="business_categories_api",
        ),
        # PRODUCT_CRUD
        path(
            "api/business/<slug:business_slug>/products/",
            business_API.business_products_api,
            name="business_products_api",
        ),
        path(
            "api/business/<slug:business_slug>/categories/",
            business_product_CRUD_API.get_business_categories,
            name="business-categories",
        ),
        path(
            "api/categories/<int:category_id>/attributes/",
            business_product_CRUD_API.get_category_attributes,
            name="category-attributes",
        ),
        # path(
        #     "api/business/<slug:business_slug>/locations/",
        #     business_product_CRUD_API.get_business_locations,
        #     name="business-locations",
        # ),
        path(
            "api/business/<slug:business_slug>/products/create/",
            business_product_CRUD_API.create_product,
            name="create-product",
        ),
        path(
            "api/business/<slug:business_slug>/products/<int:product_id>/",
            business_product_CRUD_API.get_product,
            name="detail-product",
        ),
        path(
            "api/business/<slug:business_slug>/products/<int:product_id>/info",
            business_API.get_info_product,
            name="info-product",
        ),
        path(
            "api/business/<slug:business_slug>/products/<int:product_id>/edit",
            business_product_CRUD_API.edit_product,
            name="edit-product",
        ),
        path(
            "api/business/<slug:business_slug>/products/<int:product_id>/delete",
            business_product_CRUD_API.delete_product,
            name="delete-product",
        ),
        path(
            "api/business/<slug:business_slug>/products/<int:product_id>/toggle-status/",
            business_product_CRUD_API.toggle_status_product,
            name="toggle-status-product",
        ),
        # Брак
        path(
            "api/business/<slug:business_slug>/stocks/<int:stock_id>/defects/create/",
            business_product_CRUD_API.create_stock_defect,
            name="create-stock-defect",
        ),
        path(
            "api/business/<slug:business_slug>/stocks/<int:defect_id>/defects/remove/",
            business_product_CRUD_API.remove_stock_defect,
            name="remove-stock-defect",
        ),
        # Резерв
        path(
            "api/business/<slug:business_slug>/stocks/<int:stock_id>/reserve/",
            business_product_CRUD_API.reserve_stock,
            name="reserve-stock",
        ),
        path(
            "api/business/<slug:business_slug>/stocks/<int:stock_id>/reserve/remove/",
            business_product_CRUD_API.remove_stock_reserve,
            name="remove-stock-reserve",
        ),
        # Продажа
        path(
            "api/business/<slug:business_slug>/sales-products/",
            sale_product_API.sales_products_api,
            name="sales_products_api",
        ),
        path(
            "api/business/<slug:business_slug>/create-receipt/",
            sale_product_API.create_receipt,
            name="create-receipt",
        ),
        path(
            "api/business/payment-methods/",
            sale_product_API.get_active_payment_methods,
            name="payment-methods",
        ),
        path(
            "api/business/<slug:business_slug>/dashboard/",
            analytics_API.business_dashboard,
            name="business-dashboard",
        ),
        # path(
        #     "api/business/<slug:business_slug>/receipts-in-analitycs/<str:number>/", # надо переделать в одно апи для чеков
        #     analytics_API.receipt_detail,
        #     name="receipt-detail",
        # ),
        path(
            "api/business/<slug:business_slug>/settings/",
            settings_API.business_detail_or_update,
            name="business-detail-or-update",
        ),
        path(
            "api/business/<slug:business_slug>/locations/",
            settings_API.business_locations,
            name="business-location-list-create",
        ),
        path(
            "api/business/<slug:business_slug>/locations/<int:pk>/",
            settings_API.business_location_detail,
            name="business-location-detail",
        ),
        path(
            "api/location-types/",
            settings_API.location_type_list,
            name="location-type-list",
        ),
        path(
            "api/business/<slug:business_slug>/receipts/",
            receipt_API.receipt_list,
            name="receipt-list",
        ),
        path(
            "api/business/<slug:business_slug>/receipts/<int:receipt_id>/",
            receipt_API.receipt_detail,
            name="receipt-detail",
        ),
        path(
            "api/business/<slug:business_slug>/receipts/history/",
            receipt_API.grouped_receipt_history,
            name="receipt-history",
        ),
        # path('api/business/<slug:business_slug>/products/<int:product_id>/variants/<int:variant_id>/', business_API.product_variant_detail_api, name='product_variant_detail_api'),
        # path('api/business/<slug:business_slug>/products/<int:product_id>/images/', business_API.product_images_api, name='product_images_api'),
        # path('api/business/<slug:business_slug>/products/<int:product_id>/images/<int:image_id>/', business_API.product_image_detail_api, name='product_image_detail_api'),
        # path('api/products/categories/', business_API.product_categories_api, name='product_categories_api'),
        # path(
        #     'api/business/<slug:business_slug>/products/<int:product_id>/attributes/',
        #     business_API.get_product_attributes,
        #     name='product-attributes'
        # ),
        path(
            "debug/receipt/<int:receipt_id>/html/",
            views.business_check,
            name="receipt-preview",
        ),
    ]
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blocks/footer.html
<footer class="bg-body-tertiary text-center text-md-start">
            <!-- Grid container -->
            <div class="container p-4">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Footer Content</h5>

                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                    molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                    voluptatem veniam, est atque cumque eum delectus sint!
                  </p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Links</h5>

                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#!" class="text-body">Link 1</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 2</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 3</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 4</a>
                    </li>
                  </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h5 class="text-uppercase mb-0">Links</h5>

                  <ul class="list-unstyled">
                    <li>
                      <a href="#!" class="text-body">Link 1</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 2</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 3</a>
                    </li>
                    <li>
                      <a href="#!" class="text-body">Link 4</a>
                    </li>
                  </ul>
                </div>
                <!--Grid column-->
              </div>
              <!--Grid row-->
            </div>
            <!-- Grid container -->

            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
              © 2025 Copyright:
              <a class="text-body" href="https://mdbootstrap.com/">VendorVillage.kz</a>
            </div>
            <!-- Copyright -->
          </footer>

templates/blocks/head_block.html
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
    <html lang="en" data-bs-theme="light"><head><script src="/docs/5.3/assets/js/color-modes.js"></script>
        <title>VendorVillage</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
        <!-- Favicons -->

        <style>
            
            
            .wrapper {
                flex: 1;
            }
            
            
            
            
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }

            .b-example-divider {
                width: 100%;
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
            }

            .b-example-vr {
                flex-shrink: 0;
                width: 1.5rem;
                height: 100vh;
            }

            .bi {
                vertical-align: -.125em;
                fill: currentColor;
            }

            .nav-scroller {
                position: relative;
                z-index: 2;
                height: 2.75rem;
                overflow-y: hidden;
            }

            .nav-scroller .nav {
                display: flex;
                flex-wrap: nowrap;
                padding-bottom: 1rem;
                margin-top: -1px;
                overflow-x: auto;
                text-align: center;
                white-space: nowrap;
                -webkit-overflow-scrolling: touch;
            }

            .btn-bd-primary {
                --bd-violet-bg: #712cf9;
                --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

                --bs-btn-font-weight: 600;
                --bs-btn-color: var(--bs-white);
                --bs-btn-bg: var(--bd-violet-bg);
                --bs-btn-border-color: var(--bd-violet-bg);
                --bs-btn-hover-color: var(--bs-white);
                --bs-btn-hover-bg: #6528e0;
                --bs-btn-hover-border-color: #6528e0;
                --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
                --bs-btn-active-color: var(--bs-btn-hover-color);
                --bs-btn-active-bg: #5a23c8;
                --bs-btn-active-border-color: #5a23c8;
            }

            .bd-mode-toggle {
                z-index: 1500;
            }

            .bd-mode-toggle .dropdown-menu .active .bi {
                display: block !important;
            }
            .card-img-top {
                width: 100%;
                height: 30rem; /* Можно изменить на подходящее значение */
                object-fit: cover;
            }
        </style>
        <!-- Custom styles for this template -->
        


    </head>

templates/blocks/header.html
{% load static %}

<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <div class="navbar-collapse collapse justify-content-between" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'core:main' %}">
                <img src="{% static 'icons/^.svg' %}" alt="^ Icon" width="24" height="24">
                <img src="{% static 'icons/v.svg' %}" alt="V Icon" width="24" height="24">
                VendorVillage
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:bussiness_categories_list' %}">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:sites' %}">Sites</a>
          </li>
        </ul>

        <!-- Форма поиска, выровненная по центру -->
        <form class="d-flex mx-auto" role="search">
          <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search" style="width: 400px">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <!-- Место для добавления других элементов, если нужно -->
            <li class="nav-item">
                <a class="nav-link" href="#">
                Cart
                </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{%  url 'accounts:account' %}">Account</a>
          </li>
        </ul>
      </div>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
</header>